### ISSUE TITLE
Can't get it to work? (profile used is kinda nsfw/weird)

### ISSUE THREAD

**Issue by kandicemay** [akurtovic/InstaRaider#13]
Hi, I've followed all the steps and installed selenium 2.46.0 yet I can't get it to work:

this is my terminal:

aero@ubuntu:~$ '/home/aero/InstaRaider/instaRaider.py' -u sashaovechnikova
sashaovechnikova has 12 posts on Instagram.
Loading Instagram profile...
Traceback (most recent call last):
  File "/home/aero/InstaRaider/instaRaider.py", line 203, in <module>
    source = raider.loadInstagram(url)
  File "/home/aero/InstaRaider/instaRaider.py", line 59, in loadInstagram
    element = driver.find_element_by_css_selector(self.loadLabelCssSelector)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.46.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 396, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.46.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 684, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.46.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.46.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 170, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"css selector","selector":"div.-cx-PRIVATE-AutoloadingPostsGrid__moreLoadingIndicator a"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpiwZA2W/extensions/fxdriver@googlecode.com/components/driver-component.js:10299)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmpiwZA2W/extensions/fxdriver@googlecode.com/components/driver-component.js:603)
aero@ubuntu:~$

**Comment by akurtovic** [comment]
Latest refactor failed to account for profiles with less than 24 posts, so it was failing because it was looking for the Load More button which didn't exist. It's fixed now. Pull the latest and the issue should be resolve.
