### ISSUE TITLE
User not found bug

### ISSUE THREAD

**Issue by erasmuswill** [akurtovic/InstaRaider#2]
Invalid username gives:

    Traceback (most recent call last):
      File "./instaRaider.py", line 225, in <module>
        count = raider.getImageCount(url)
      File "./instaRaider.py", line 26, in getImageCount
        response = urllib2.urlopen(url)
      File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 410, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 442, in error
        result = self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/usr/lib/python2.7/urllib2.py", line 410, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 448, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 404: NOT FOUND

The last block of code:

    if(raider.validUser(userName)):
        # Get source code from fully loaded Instagram profile page
        source = raider.loadInstagram(url)

        # Download all photos identified on profile page
        raider.getPhotos(source, userName, count)
    else:
        print "Username " + userName + " is not valid."

seems to check if the username is valid or not, but it's obviously not working.

**Comment by erasmuswill** [comment]
Doing:
            # check if Instagram username is valid
            req = urllib2.Request(self.profileUrl)

            try:
                urllib2.urlopen(req)
            except:
                valid = False
            # if req doesn't fail, user profile exists
            return valid

in an alternate terminal works, though:

    >>> import urllib2
    >>> req = urllib2.Request('http://instagram.com/erasmuswill')
    >>> try:
    ...     urllib2.urlopen(req)
    ... except:
    ...     print("nope")
    ... 
    nope

**Comment by akurtovic** [comment]
I just fixed this bug. I haven't touched this project in a few months and just realized that Instagram's HTML structure had changed a lot, which was causing a lot of issues. Everything should work fine now. Open another issue if the latest code gives you troubles.
