### ISSUE TITLE
Redirected to Login Page.

### ISSUE THREAD

**Issue by NutellaCoatedBacon** [akurtovic/InstaRaider#29]
Whenever I try and raid a private instagram page I keep being redirected to the login page for the site. I keep getting "You need to login to access this profile. Redirecting you to the login page in the browser." which makes no sense because I am using the build that allows you to raid private pages. There are also some issues that come along with it. 

Traceback (most recent call last):
  File "instaRaider.py", line 257, in <module>
    main()
  File "instaRaider.py", line 253, in main
    raider.download_photos()
  File "instaRaider.py", line 199, in download_photos
    self.html_source = self.load_instagram()
  File "instaRaider.py", line 133, in load_instagram
    self.log_in_user()
  File "instaRaider.py", line 101, in log_in_user
    (By.CSS_SELECTOR, '.-cx-PRIVATE-FeedPage__feed'),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmp6DVsTU/extensions/fxdriver@googlecode.com/components/driver-component.js:10647)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmp6DVsTU/extensions/fxdriver@googlecode.com/components/driver-component.js:623)

I have to program running but I keep hitting this, what can I do?

Quick Update: It works on public profiles but not private.

**Comment by rick9791** [comment]
The script won't work if you aren't following a private profile.
