### ISSUE TITLE
selenium error

### ISSUE THREAD

**Issue by adrianmihalko** [akurtovic/InstaRaider#33]
Here is the error what I get when I am trying to run InstaRaider:
```
@ubuntu:~/temp/InstaRaider$ ./instaRaider.py kryptonitelock ./kryptonitelock
Traceback (most recent call last):
  File "./instaRaider.py", line 257, in <module>
    main()
  File "./instaRaider.py", line 248, in main
    log_level=args.log_level)
  File "./instaRaider.py", line 55, in __init__
    self.setup_webdriver()
  File "./instaRaider.py", line 76, in setup_webdriver
    self.webdriver = webdriver.Firefox(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 70, in __init__
    self.binary = FirefoxBinary()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 47, in __init__
    self._start_cmd = self._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 159, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
```

selenium is the latest one selenium-2.48.0

**Comment by akurtovic** [comment]
If you haven't solved this already, I suggest checking the version of your Firefox to make sure it's compatible with that version of selenium. Here's the CHANGELOG: https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG
