### ISSUE TITLE
bash-3.2# python instaRaider.py -n 28 saracerdem ./images/yunusay/ 

### ISSUE THREAD

**Issue by yunusay** [akurtovic/InstaRaider#40]
Hi @akurtovic 
i'm macosx el capitan 10.11.1 using but I do not understand the problems faced... :/

What is wrong.. please help?

<code>bash-3.2# python instaRaider.py -n 100 yunusay ./images/yunusay/
Traceback (most recent call last):
  File "instaRaider.py", line 439, in <module>
    main()
  File "instaRaider.py", line 429, in main
    get_videos=args.get_videos)
  File "instaRaider.py", line 63, in **init**
    self.setup_webdriver()
  File "instaRaider.py", line 88, in setup_webdriver
    self.webdriver = webdriver.Firefox(self.profile)
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 77, in **init**
    self.binary, timeout),
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/extension_connection.py", line 49, in **init**
    self.binary.launch_browser(self.profile)
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by akurtovic** [comment]
For a quick glance at the stack trace it looks like an issue with your selenium driver, but I can't reproduce this exactly since your profile is private. I would try reinstalling selenium. Let me know if that doesn't work and I can look into it more.
