### ISSUE TITLE
I can't use InstaRaider to download photos from private profiles

### ISSUE THREAD

**Issue by rick9791** [akurtovic/InstaRaider#53]
Downloading photos from private profile doesn't work anymore, if I try to download a private profile, I get these messages:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\Python27>python.exe c:\Python27\Scripts\InstaRaider-master\instaRaider.py ines.aragao c:\Python27
ines.aragao has 239 posts on Instagram.
Loading Instagram profile...
Traceback (most recent call last):
  File "c:\Python27\Scripts\InstaRaider-master\instaRaider.py", line 484, in <module>
    main()
  File "c:\Python27\Scripts\InstaRaider-master\instaRaider.py", line 479, in main
    raider.download_photos()
  File "c:\Python27\Scripts\InstaRaider-master\instaRaider.py", line 224, in download_photos
    self.html_source = self.load_instagram()
  File "c:\Python27\Scripts\InstaRaider-master\instaRaider.py", line 174, in load_instagram
    element = driver.find_element_by_css_selector('a._oidfu')
  File "c:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 402, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "c:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "c:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "c:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"css selector","selector":"a._oidfu"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///c:/users/user/appdata/local/temp/tmp60ma0g/extensions/fxdriver@googlecode.com/components/driver-
component.js:10723)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///c:/users/user/appdata/local/temp/tmp60ma0g/extensions/fxdriver@googlecode.com/components/driver-
component.js:623)
```

Even if I trigger the script to make me login to my profile, it just redirects me to https://www.instagram.com/ rather than the profile that I am trying to download photos from.

**Comment by dluxcru** [comment]
I can't imagine that's SUPPOSED to work.
