### ISSUE TITLE
How should I provide directory, I tried everything.

### ISSUE THREAD

**Issue by rahul3103** [akurtovic/InstaRaider#54]
`InstaRaider $ python instaRaider.py -n 301 username  /Users/rahul/projects/personal/
Traceback (most recent call last):
  File "instaRaider.py", line 484, in <module>
    main()
  File "instaRaider.py", line 474, in main
    process_number=args.process_number)
  File "instaRaider.py", line 87, in __init__
    self.setup_webdriver()
  File "instaRaider.py", line 113, in setup_webdriver
    self.webdriver = webdriver.Firefox(self.profile)
  File "/Users/rahul/.virtualenvs/fifa/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "/Users/rahul/.virtualenvs/fifa/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Users/rahul/.virtualenvs/fifa/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Users/rahul/.virtualenvs/fifa/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by rahul3103** [comment]
I tried python instaRaider.py -n 301 username ./Users/rahul/projects/personal/ and python instaRaider.py -n 301 username ~/Users/rahul/projects/personal/
