### ISSUE TITLE
script crash after last update firefox

### ISSUE THREAD

**Issue by Fantasim** [akurtovic/InstaRaider#55]
hey,

Since the last update of firefox, instaRaider crash with this error (i have make others bots with selenium and i've the same problem)

this is error

```
Traceback (most recent call last):
  File "instaRaider.py", line 484, in <module>
    main()
  File "instaRaider.py", line 474, in main
    process_number=args.process_number)
  File "instaRaider.py", line 87, in __init__
    self.setup_webdriver()
  File "instaRaider.py", line 113, in setup_webdriver
    self.webdriver = webdriver.Firefox(self.profile)
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 103, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.

```

have u an idea to how fix it?

**Comment by imaginology** [comment]
Same here. Tried update to selenium as suggested in previous posts to no resolve. Anyone...?
