### ISSUE TITLE
Error anytime I try to raid more than 60 photos.

### ISSUE THREAD

**Issue by dannyvoid** [akurtovic/InstaRaider#7]
This error pops up anytime I try to raid 61 or more photos from any account. 

    F:\Google Drive\Raider>instaRaider.py -u username -c 80
    username has 215 photos on Instagram.
    Loading Selenium WebDriver...
    Loading Instagram profile...
    ...Traceback (most recent call last):
      File "F:\Google Drive\Raider\instaRaider.py", line 237, in <module>
        source = raider.loadInstagram(url)
      File "F:\Google Drive\Raider\instaRaider.py", line 73, in loadInstagram
        element = driver.find_element_by_css_selector(self.loadLabelCssSelector)
      File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
    ine 376, in find_element_by_css_selector
        return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
      File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
    ine 664, in find_element
        {'using': by, 'value': value})['value']
      File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
    ine 175, in execute
        self.error_handler.check_response(response)
      File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py"
    , line 166, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.NoSuchElementException: Message: Unable to locate ele
    ment: {"method":"css selector","selector":"body > div.root > div > div > div > d
    iv.mbMedia > div.ResponsiveBlock > button > span"}
    Stacktrace:
        at FirefoxDriver.prototype.findElementInternal_ (file:///c:/users/daniel/app
    data/local/temp/tmpf26dwy/extensions/fxdriver@googlecode.com/components/driver-c
    omponent.js:10271)
        at fxdriver.Timer.prototype.setTimeout/<.notify (file:///c:/users/daniel/app
    data/local/temp/tmpf26dwy/extensions/fxdriver@googlecode.com/components/driver-c
    omponent.js:603)

**Comment by akurtovic** [comment]
You're seeing this error because the CSS selector for the "Load More" label has changed on Instagram. The reason you only see this when you try to get more than 60 photos is that the label only shows up after the third set of 20 images loads using the scroll. I'll update the CSS selector and push the code in a few minutes. It should work again after that.
