### ISSUE TITLE
Selenium opens up an empty firefox window and then hangs

### ISSUE THREAD

**Issue by jaymzh** [akurtovic/InstaRaider#8]
I just get a firefox window ... and that's it, then it hangs. If I close it, then it crashes witth a traceback:

```
Traceback (most recent call last):
  File "/home/phil/build/git/InstaRaider/instaRaider.py", line 241, in <module>
    source = raider.loadInstagram(url)
  File "/home/phil/build/git/InstaRaider/instaRaider.py", line 43, in loadInstagram
    driver = webdriver.Firefox()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 46, in __init__
    self.binary, timeout),
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 46, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 44, in launch_browser
    self._wait_until_connectable() 
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 87, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile Dir : %s" % self.profile.path)
selenium.common.exceptions.WebDriverException: Message: "Can't load the profile. Profile Dir : /tmp/tmpytWE05" 
```

**Comment by akurtovic** [comment]
Your issue seems to be related to this: http://stackoverflow.com/questions/6682009/selenium-firefoxprofile-exception-cant-load-the-profile

Can you do a:
```
sudo pip install -U selenium
```
and let me know if that fixes the issue.

**Comment by jaymzh** [comment]
Yup. That's working. Thanks for the quick response!

Your docs correctly say to install selenium this way, but since it was packaged in debian already, I preferred that. If you add a note in there that the version packaged in debian/ubuntu has a bug you may prevent future similar bugs.

**Comment by akurtovic** [comment]
Cool. Glad it's working. I'll update the docs to reflect that.

**Comment by sundarkh** [comment]
still seeing this issue in selenium 2.52.0 with Ubuntu 14.4 LTS, python 2.7 environment, can you help

**Comment by EmreYavuz216** [comment]
Still seeing this issue in selenium 2.53.6 with Mac Os python 3.4 environment

**Comment by distantstar** [comment]
I actually get it too 

` $ pip list
pip (8.1.2)
requests (2.11.1)
selenium (2.53.6)
setuptools (18.2)
urllib3 (1.16)
wheel (0.24.0)`

At this point, it might be better to upgrade to selenium3 and rewrite the script. I think every Firefox upgrade from now on will break the script.
